# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mwU4LfY4g-sf07zrkBl-EPKCvKpgWjbv
"""

import numpy as plt
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data = pd.read_csv('/content/Titanic-Dataset.csv')
print(data)

import numpy as np
from scipy import stats
mean1 = np.mean(data['Age'])
median1 = np.median(data['Age'])
mode1=stats.mode(data['Age'],keepdims = True).mode[0]
mean2 = np.mean(data['Fare'])
median2 = np.median(data['Fare'])
mode2=stats.mode(data['Fare'],keepdims = True).mode[0]
print("Central Trndency:")
print("mean Age:",mean1)
print("median Age:",median1)
print("mode Age:",mode1)
print("mean Fare:",mean2)
print("median Fare:",median2)
print("mode Fare:",mode2)

import pandas as pd
import matplotlib.pyplot as plt
grouped_data = data.groupby(['Survived', 'Pclass']) ['PassengerId'].count().unstack()
grouped_data.plot(kind='bar', figsize=(10, 6))
plt.title('Survival Counts by Pclass')
plt.xlabel('Survival')
plt.ylabel('Count')
plt.xticks(ticks=[0, 1], labels= ['Not Survived', 'Survived'], rotation=0)
plt.legend(title='Pclass')
plt.show()

import pandas as pd
data
null_values=data.isnull().sum()
data_filled=data.fillna(data.mean(numeric_only=True))
null_values, data_filled.head()

import numpy as np
mean=np.mean(data['Age'])
std=np.std(data['Age'])
print('mean of the dataset is', mean)
print('std. deviation is', std)

threshold=3
outlier=[]
for i in data['Age']:
      z=(i-mean)/std
      if z>threshold:
          outlier.append(i);
print('outliers are', outlier)

import seaborn as sns
sns.boxplot(data['Age'])

